### ISSUE TITLE
DialogService need help

### ISSUE THREAD

**Issue by jcpc91** [lbugnion/mvvmlight#54]
on android i get error when i try to showMessage  
--- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
	at android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:224)
	at android.app.AlertDialog$Builder.<init>(AlertDialog.java:454)
	at md58432a647068b097f9637064b8985a5e0.ButtonRenderer_ButtonClickListener.n_onClick(Native Method)
	at md58432a647068b097f9637064b8985a5e0.ButtonRenderer_ButtonClickListener.onClick(ButtonRenderer_ButtonClickListener.java:30)
	at android.view.View.performClick(View.java:6294)
	at android.view.View$PerformClick.run(View.java:24770)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

thanks

**Comment by phillippbertram** [comment]
Even if this answer comes a little late, I still hope that it can help others. I also encountered this problem and found that I registered `DialogService` instead of `AppCompatDialogService`.
My `Activities` inherit from `AppCompatActivityBase` and not from `ActivityBase` ✌️
