### ISSUE TITLE
System.OutOfMemoryException when trying to send message

### ISSUE THREAD

**Issue by EnomisG** [lbugnion/mvvmlight#78]
Sometimes when sending a message a OutOfMemoryException was thrown.
```
An unhandled exception just occurred|System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GalaSoft.MvvmLight.Messaging.Messenger.SendToTargetOrType[TMessage](TMessage message, Type messageTargetType, Object token) in c:\MvvmLight\Source\GalaSoft.MvvmLight\GalaSoft.MvvmLight (PCL)\Messaging\Messenger.cs:line 669
   at GalaSoft.MvvmLight.Messaging.Messenger.Send[TMessage](TMessage message) in c:\MvvmLight\Source\GalaSoft.MvvmLight\GalaSoft.MvvmLight (PCL)\Messaging\Messenger.cs:line 259
```

**Comment by LeiYangGH** [comment]
is there a demo to reproduce this issue?

**Comment by Eagle3386** [comment]
Maybe related to #65? 🤔
